-- Networking tracker: contacts table, RLS, and ownership policies.
-- Run once via `npm run migrate` (backend/db/migrate.ts) or paste into the
-- Neon SQL editor. Safe to re-run: uses IF NOT EXISTS / OR REPLACE / DROP+CREATE
-- for policies so it can be applied idempotently.

create table if not exists contacts (
  id bigint generated by default as identity primary key,
  user_id text not null default auth.user_id(),
  name text not null,
  company text,
  role text,
  where_met text,
  notes text,
  priority text not null check (priority in ('low', 'medium', 'high')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table contacts enable row level security;

drop policy if exists contacts_select_own on contacts;
create policy contacts_select_own on contacts
  for select to authenticated
  using (auth.user_id() = user_id);

drop policy if exists contacts_insert_own on contacts;
create policy contacts_insert_own on contacts
  for insert to authenticated
  with check (auth.user_id() = user_id);

drop policy if exists contacts_update_own on contacts;
create policy contacts_update_own on contacts
  for update to authenticated
  using (auth.user_id() = user_id)
  with check (auth.user_id() = user_id); -- blocks reassigning a row to another user

drop policy if exists contacts_delete_own on contacts;
create policy contacts_delete_own on contacts
  for delete to authenticated
  using (auth.user_id() = user_id);

grant select, insert, update, delete on contacts to authenticated;
grant usage, select on sequence contacts_id_seq to authenticated;
